/*
**  SwizzleGen is a tool to generate swizzle permutations for differents languages.
**
**  MIT License
**  Copyright (c) 2020  z0rg - Sebastien Maire
**
**  Permission is hereby granted, free of charge, to any person obtaining a copy
**  of this software and associated documentation files (the "Software"), to deal
**  in the Software without restriction, including without limitation the rights
**  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
**  copies of the Software, and to permit persons to whom the Software is
**  furnished to do so, subject to the following conditions:
**
**  The above copyright notice and this permission notice shall be included in all
**  copies or substantial portions of the Software.
**
**  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
**  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
**  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
**  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
**  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
**  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
**  SOFTWARE.
*/

#pragma once

// Swizzle is implemented using uppercase letters so we can match implem in GLSL and CPP
// for cpp it ends up being vec3.XY_ = vec2(1.,2.) whichs translates to vec3.xy() = vec2(1.,2.) with the 
// matching function being defined in vector the class

#ifdef OPENGL_SHADER_CODE
#define SWIZZLE_SUFFIX
#else
#define SWIZZLE_SUFFIX ()
#endif // OPENGL_SHADER_CODE

// Swizzle xyzw
// Swizzle xyzw with 1 components.
#define X_ x SWIZZLE_SUFFIX
#define Y_ y SWIZZLE_SUFFIX
#define Z_ z SWIZZLE_SUFFIX
#define W_ w SWIZZLE_SUFFIX

// Swizzle xyzw with 2 components.
#define XX_ xx SWIZZLE_SUFFIX
#define YX_ yx SWIZZLE_SUFFIX
#define ZX_ zx SWIZZLE_SUFFIX
#define WX_ wx SWIZZLE_SUFFIX
#define XY_ xy SWIZZLE_SUFFIX
#define YY_ yy SWIZZLE_SUFFIX
#define ZY_ zy SWIZZLE_SUFFIX
#define WY_ wy SWIZZLE_SUFFIX
#define XZ_ xz SWIZZLE_SUFFIX
#define YZ_ yz SWIZZLE_SUFFIX
#define ZZ_ zz SWIZZLE_SUFFIX
#define WZ_ wz SWIZZLE_SUFFIX
#define XW_ xw SWIZZLE_SUFFIX
#define YW_ yw SWIZZLE_SUFFIX
#define ZW_ zw SWIZZLE_SUFFIX
#define WW_ ww SWIZZLE_SUFFIX

// Swizzle xyzw with 3 components.
#define XXX_ xxx SWIZZLE_SUFFIX
#define YXX_ yxx SWIZZLE_SUFFIX
#define ZXX_ zxx SWIZZLE_SUFFIX
#define WXX_ wxx SWIZZLE_SUFFIX
#define XYX_ xyx SWIZZLE_SUFFIX
#define YYX_ yyx SWIZZLE_SUFFIX
#define ZYX_ zyx SWIZZLE_SUFFIX
#define WYX_ wyx SWIZZLE_SUFFIX
#define XZX_ xzx SWIZZLE_SUFFIX
#define YZX_ yzx SWIZZLE_SUFFIX
#define ZZX_ zzx SWIZZLE_SUFFIX
#define WZX_ wzx SWIZZLE_SUFFIX
#define XWX_ xwx SWIZZLE_SUFFIX
#define YWX_ ywx SWIZZLE_SUFFIX
#define ZWX_ zwx SWIZZLE_SUFFIX
#define WWX_ wwx SWIZZLE_SUFFIX
#define XXY_ xxy SWIZZLE_SUFFIX
#define YXY_ yxy SWIZZLE_SUFFIX
#define ZXY_ zxy SWIZZLE_SUFFIX
#define WXY_ wxy SWIZZLE_SUFFIX
#define XYY_ xyy SWIZZLE_SUFFIX
#define YYY_ yyy SWIZZLE_SUFFIX
#define ZYY_ zyy SWIZZLE_SUFFIX
#define WYY_ wyy SWIZZLE_SUFFIX
#define XZY_ xzy SWIZZLE_SUFFIX
#define YZY_ yzy SWIZZLE_SUFFIX
#define ZZY_ zzy SWIZZLE_SUFFIX
#define WZY_ wzy SWIZZLE_SUFFIX
#define XWY_ xwy SWIZZLE_SUFFIX
#define YWY_ ywy SWIZZLE_SUFFIX
#define ZWY_ zwy SWIZZLE_SUFFIX
#define WWY_ wwy SWIZZLE_SUFFIX
#define XXZ_ xxz SWIZZLE_SUFFIX
#define YXZ_ yxz SWIZZLE_SUFFIX
#define ZXZ_ zxz SWIZZLE_SUFFIX
#define WXZ_ wxz SWIZZLE_SUFFIX
#define XYZ_ xyz SWIZZLE_SUFFIX
#define YYZ_ yyz SWIZZLE_SUFFIX
#define ZYZ_ zyz SWIZZLE_SUFFIX
#define WYZ_ wyz SWIZZLE_SUFFIX
#define XZZ_ xzz SWIZZLE_SUFFIX
#define YZZ_ yzz SWIZZLE_SUFFIX
#define ZZZ_ zzz SWIZZLE_SUFFIX
#define WZZ_ wzz SWIZZLE_SUFFIX
#define XWZ_ xwz SWIZZLE_SUFFIX
#define YWZ_ ywz SWIZZLE_SUFFIX
#define ZWZ_ zwz SWIZZLE_SUFFIX
#define WWZ_ wwz SWIZZLE_SUFFIX
#define XXW_ xxw SWIZZLE_SUFFIX
#define YXW_ yxw SWIZZLE_SUFFIX
#define ZXW_ zxw SWIZZLE_SUFFIX
#define WXW_ wxw SWIZZLE_SUFFIX
#define XYW_ xyw SWIZZLE_SUFFIX
#define YYW_ yyw SWIZZLE_SUFFIX
#define ZYW_ zyw SWIZZLE_SUFFIX
#define WYW_ wyw SWIZZLE_SUFFIX
#define XZW_ xzw SWIZZLE_SUFFIX
#define YZW_ yzw SWIZZLE_SUFFIX
#define ZZW_ zzw SWIZZLE_SUFFIX
#define WZW_ wzw SWIZZLE_SUFFIX
#define XWW_ xww SWIZZLE_SUFFIX
#define YWW_ yww SWIZZLE_SUFFIX
#define ZWW_ zww SWIZZLE_SUFFIX
#define WWW_ www SWIZZLE_SUFFIX

// Swizzle xyzw with 4 components.
#define XXXX_ xxxx SWIZZLE_SUFFIX
#define YXXX_ yxxx SWIZZLE_SUFFIX
#define ZXXX_ zxxx SWIZZLE_SUFFIX
#define WXXX_ wxxx SWIZZLE_SUFFIX
#define XYXX_ xyxx SWIZZLE_SUFFIX
#define YYXX_ yyxx SWIZZLE_SUFFIX
#define ZYXX_ zyxx SWIZZLE_SUFFIX
#define WYXX_ wyxx SWIZZLE_SUFFIX
#define XZXX_ xzxx SWIZZLE_SUFFIX
#define YZXX_ yzxx SWIZZLE_SUFFIX
#define ZZXX_ zzxx SWIZZLE_SUFFIX
#define WZXX_ wzxx SWIZZLE_SUFFIX
#define XWXX_ xwxx SWIZZLE_SUFFIX
#define YWXX_ ywxx SWIZZLE_SUFFIX
#define ZWXX_ zwxx SWIZZLE_SUFFIX
#define WWXX_ wwxx SWIZZLE_SUFFIX
#define XXYX_ xxyx SWIZZLE_SUFFIX
#define YXYX_ yxyx SWIZZLE_SUFFIX
#define ZXYX_ zxyx SWIZZLE_SUFFIX
#define WXYX_ wxyx SWIZZLE_SUFFIX
#define XYYX_ xyyx SWIZZLE_SUFFIX
#define YYYX_ yyyx SWIZZLE_SUFFIX
#define ZYYX_ zyyx SWIZZLE_SUFFIX
#define WYYX_ wyyx SWIZZLE_SUFFIX
#define XZYX_ xzyx SWIZZLE_SUFFIX
#define YZYX_ yzyx SWIZZLE_SUFFIX
#define ZZYX_ zzyx SWIZZLE_SUFFIX
#define WZYX_ wzyx SWIZZLE_SUFFIX
#define XWYX_ xwyx SWIZZLE_SUFFIX
#define YWYX_ ywyx SWIZZLE_SUFFIX
#define ZWYX_ zwyx SWIZZLE_SUFFIX
#define WWYX_ wwyx SWIZZLE_SUFFIX
#define XXZX_ xxzx SWIZZLE_SUFFIX
#define YXZX_ yxzx SWIZZLE_SUFFIX
#define ZXZX_ zxzx SWIZZLE_SUFFIX
#define WXZX_ wxzx SWIZZLE_SUFFIX
#define XYZX_ xyzx SWIZZLE_SUFFIX
#define YYZX_ yyzx SWIZZLE_SUFFIX
#define ZYZX_ zyzx SWIZZLE_SUFFIX
#define WYZX_ wyzx SWIZZLE_SUFFIX
#define XZZX_ xzzx SWIZZLE_SUFFIX
#define YZZX_ yzzx SWIZZLE_SUFFIX
#define ZZZX_ zzzx SWIZZLE_SUFFIX
#define WZZX_ wzzx SWIZZLE_SUFFIX
#define XWZX_ xwzx SWIZZLE_SUFFIX
#define YWZX_ ywzx SWIZZLE_SUFFIX
#define ZWZX_ zwzx SWIZZLE_SUFFIX
#define WWZX_ wwzx SWIZZLE_SUFFIX
#define XXWX_ xxwx SWIZZLE_SUFFIX
#define YXWX_ yxwx SWIZZLE_SUFFIX
#define ZXWX_ zxwx SWIZZLE_SUFFIX
#define WXWX_ wxwx SWIZZLE_SUFFIX
#define XYWX_ xywx SWIZZLE_SUFFIX
#define YYWX_ yywx SWIZZLE_SUFFIX
#define ZYWX_ zywx SWIZZLE_SUFFIX
#define WYWX_ wywx SWIZZLE_SUFFIX
#define XZWX_ xzwx SWIZZLE_SUFFIX
#define YZWX_ yzwx SWIZZLE_SUFFIX
#define ZZWX_ zzwx SWIZZLE_SUFFIX
#define WZWX_ wzwx SWIZZLE_SUFFIX
#define XWWX_ xwwx SWIZZLE_SUFFIX
#define YWWX_ ywwx SWIZZLE_SUFFIX
#define ZWWX_ zwwx SWIZZLE_SUFFIX
#define WWWX_ wwwx SWIZZLE_SUFFIX
#define XXXY_ xxxy SWIZZLE_SUFFIX
#define YXXY_ yxxy SWIZZLE_SUFFIX
#define ZXXY_ zxxy SWIZZLE_SUFFIX
#define WXXY_ wxxy SWIZZLE_SUFFIX
#define XYXY_ xyxy SWIZZLE_SUFFIX
#define YYXY_ yyxy SWIZZLE_SUFFIX
#define ZYXY_ zyxy SWIZZLE_SUFFIX
#define WYXY_ wyxy SWIZZLE_SUFFIX
#define XZXY_ xzxy SWIZZLE_SUFFIX
#define YZXY_ yzxy SWIZZLE_SUFFIX
#define ZZXY_ zzxy SWIZZLE_SUFFIX
#define WZXY_ wzxy SWIZZLE_SUFFIX
#define XWXY_ xwxy SWIZZLE_SUFFIX
#define YWXY_ ywxy SWIZZLE_SUFFIX
#define ZWXY_ zwxy SWIZZLE_SUFFIX
#define WWXY_ wwxy SWIZZLE_SUFFIX
#define XXYY_ xxyy SWIZZLE_SUFFIX
#define YXYY_ yxyy SWIZZLE_SUFFIX
#define ZXYY_ zxyy SWIZZLE_SUFFIX
#define WXYY_ wxyy SWIZZLE_SUFFIX
#define XYYY_ xyyy SWIZZLE_SUFFIX
#define YYYY_ yyyy SWIZZLE_SUFFIX
#define ZYYY_ zyyy SWIZZLE_SUFFIX
#define WYYY_ wyyy SWIZZLE_SUFFIX
#define XZYY_ xzyy SWIZZLE_SUFFIX
#define YZYY_ yzyy SWIZZLE_SUFFIX
#define ZZYY_ zzyy SWIZZLE_SUFFIX
#define WZYY_ wzyy SWIZZLE_SUFFIX
#define XWYY_ xwyy SWIZZLE_SUFFIX
#define YWYY_ ywyy SWIZZLE_SUFFIX
#define ZWYY_ zwyy SWIZZLE_SUFFIX
#define WWYY_ wwyy SWIZZLE_SUFFIX
#define XXZY_ xxzy SWIZZLE_SUFFIX
#define YXZY_ yxzy SWIZZLE_SUFFIX
#define ZXZY_ zxzy SWIZZLE_SUFFIX
#define WXZY_ wxzy SWIZZLE_SUFFIX
#define XYZY_ xyzy SWIZZLE_SUFFIX
#define YYZY_ yyzy SWIZZLE_SUFFIX
#define ZYZY_ zyzy SWIZZLE_SUFFIX
#define WYZY_ wyzy SWIZZLE_SUFFIX
#define XZZY_ xzzy SWIZZLE_SUFFIX
#define YZZY_ yzzy SWIZZLE_SUFFIX
#define ZZZY_ zzzy SWIZZLE_SUFFIX
#define WZZY_ wzzy SWIZZLE_SUFFIX
#define XWZY_ xwzy SWIZZLE_SUFFIX
#define YWZY_ ywzy SWIZZLE_SUFFIX
#define ZWZY_ zwzy SWIZZLE_SUFFIX
#define WWZY_ wwzy SWIZZLE_SUFFIX
#define XXWY_ xxwy SWIZZLE_SUFFIX
#define YXWY_ yxwy SWIZZLE_SUFFIX
#define ZXWY_ zxwy SWIZZLE_SUFFIX
#define WXWY_ wxwy SWIZZLE_SUFFIX
#define XYWY_ xywy SWIZZLE_SUFFIX
#define YYWY_ yywy SWIZZLE_SUFFIX
#define ZYWY_ zywy SWIZZLE_SUFFIX
#define WYWY_ wywy SWIZZLE_SUFFIX
#define XZWY_ xzwy SWIZZLE_SUFFIX
#define YZWY_ yzwy SWIZZLE_SUFFIX
#define ZZWY_ zzwy SWIZZLE_SUFFIX
#define WZWY_ wzwy SWIZZLE_SUFFIX
#define XWWY_ xwwy SWIZZLE_SUFFIX
#define YWWY_ ywwy SWIZZLE_SUFFIX
#define ZWWY_ zwwy SWIZZLE_SUFFIX
#define WWWY_ wwwy SWIZZLE_SUFFIX
#define XXXZ_ xxxz SWIZZLE_SUFFIX
#define YXXZ_ yxxz SWIZZLE_SUFFIX
#define ZXXZ_ zxxz SWIZZLE_SUFFIX
#define WXXZ_ wxxz SWIZZLE_SUFFIX
#define XYXZ_ xyxz SWIZZLE_SUFFIX
#define YYXZ_ yyxz SWIZZLE_SUFFIX
#define ZYXZ_ zyxz SWIZZLE_SUFFIX
#define WYXZ_ wyxz SWIZZLE_SUFFIX
#define XZXZ_ xzxz SWIZZLE_SUFFIX
#define YZXZ_ yzxz SWIZZLE_SUFFIX
#define ZZXZ_ zzxz SWIZZLE_SUFFIX
#define WZXZ_ wzxz SWIZZLE_SUFFIX
#define XWXZ_ xwxz SWIZZLE_SUFFIX
#define YWXZ_ ywxz SWIZZLE_SUFFIX
#define ZWXZ_ zwxz SWIZZLE_SUFFIX
#define WWXZ_ wwxz SWIZZLE_SUFFIX
#define XXYZ_ xxyz SWIZZLE_SUFFIX
#define YXYZ_ yxyz SWIZZLE_SUFFIX
#define ZXYZ_ zxyz SWIZZLE_SUFFIX
#define WXYZ_ wxyz SWIZZLE_SUFFIX
#define XYYZ_ xyyz SWIZZLE_SUFFIX
#define YYYZ_ yyyz SWIZZLE_SUFFIX
#define ZYYZ_ zyyz SWIZZLE_SUFFIX
#define WYYZ_ wyyz SWIZZLE_SUFFIX
#define XZYZ_ xzyz SWIZZLE_SUFFIX
#define YZYZ_ yzyz SWIZZLE_SUFFIX
#define ZZYZ_ zzyz SWIZZLE_SUFFIX
#define WZYZ_ wzyz SWIZZLE_SUFFIX
#define XWYZ_ xwyz SWIZZLE_SUFFIX
#define YWYZ_ ywyz SWIZZLE_SUFFIX
#define ZWYZ_ zwyz SWIZZLE_SUFFIX
#define WWYZ_ wwyz SWIZZLE_SUFFIX
#define XXZZ_ xxzz SWIZZLE_SUFFIX
#define YXZZ_ yxzz SWIZZLE_SUFFIX
#define ZXZZ_ zxzz SWIZZLE_SUFFIX
#define WXZZ_ wxzz SWIZZLE_SUFFIX
#define XYZZ_ xyzz SWIZZLE_SUFFIX
#define YYZZ_ yyzz SWIZZLE_SUFFIX
#define ZYZZ_ zyzz SWIZZLE_SUFFIX
#define WYZZ_ wyzz SWIZZLE_SUFFIX
#define XZZZ_ xzzz SWIZZLE_SUFFIX
#define YZZZ_ yzzz SWIZZLE_SUFFIX
#define ZZZZ_ zzzz SWIZZLE_SUFFIX
#define WZZZ_ wzzz SWIZZLE_SUFFIX
#define XWZZ_ xwzz SWIZZLE_SUFFIX
#define YWZZ_ ywzz SWIZZLE_SUFFIX
#define ZWZZ_ zwzz SWIZZLE_SUFFIX
#define WWZZ_ wwzz SWIZZLE_SUFFIX
#define XXWZ_ xxwz SWIZZLE_SUFFIX
#define YXWZ_ yxwz SWIZZLE_SUFFIX
#define ZXWZ_ zxwz SWIZZLE_SUFFIX
#define WXWZ_ wxwz SWIZZLE_SUFFIX
#define XYWZ_ xywz SWIZZLE_SUFFIX
#define YYWZ_ yywz SWIZZLE_SUFFIX
#define ZYWZ_ zywz SWIZZLE_SUFFIX
#define WYWZ_ wywz SWIZZLE_SUFFIX
#define XZWZ_ xzwz SWIZZLE_SUFFIX
#define YZWZ_ yzwz SWIZZLE_SUFFIX
#define ZZWZ_ zzwz SWIZZLE_SUFFIX
#define WZWZ_ wzwz SWIZZLE_SUFFIX
#define XWWZ_ xwwz SWIZZLE_SUFFIX
#define YWWZ_ ywwz SWIZZLE_SUFFIX
#define ZWWZ_ zwwz SWIZZLE_SUFFIX
#define WWWZ_ wwwz SWIZZLE_SUFFIX
#define XXXW_ xxxw SWIZZLE_SUFFIX
#define YXXW_ yxxw SWIZZLE_SUFFIX
#define ZXXW_ zxxw SWIZZLE_SUFFIX
#define WXXW_ wxxw SWIZZLE_SUFFIX
#define XYXW_ xyxw SWIZZLE_SUFFIX
#define YYXW_ yyxw SWIZZLE_SUFFIX
#define ZYXW_ zyxw SWIZZLE_SUFFIX
#define WYXW_ wyxw SWIZZLE_SUFFIX
#define XZXW_ xzxw SWIZZLE_SUFFIX
#define YZXW_ yzxw SWIZZLE_SUFFIX
#define ZZXW_ zzxw SWIZZLE_SUFFIX
#define WZXW_ wzxw SWIZZLE_SUFFIX
#define XWXW_ xwxw SWIZZLE_SUFFIX
#define YWXW_ ywxw SWIZZLE_SUFFIX
#define ZWXW_ zwxw SWIZZLE_SUFFIX
#define WWXW_ wwxw SWIZZLE_SUFFIX
#define XXYW_ xxyw SWIZZLE_SUFFIX
#define YXYW_ yxyw SWIZZLE_SUFFIX
#define ZXYW_ zxyw SWIZZLE_SUFFIX
#define WXYW_ wxyw SWIZZLE_SUFFIX
#define XYYW_ xyyw SWIZZLE_SUFFIX
#define YYYW_ yyyw SWIZZLE_SUFFIX
#define ZYYW_ zyyw SWIZZLE_SUFFIX
#define WYYW_ wyyw SWIZZLE_SUFFIX
#define XZYW_ xzyw SWIZZLE_SUFFIX
#define YZYW_ yzyw SWIZZLE_SUFFIX
#define ZZYW_ zzyw SWIZZLE_SUFFIX
#define WZYW_ wzyw SWIZZLE_SUFFIX
#define XWYW_ xwyw SWIZZLE_SUFFIX
#define YWYW_ ywyw SWIZZLE_SUFFIX
#define ZWYW_ zwyw SWIZZLE_SUFFIX
#define WWYW_ wwyw SWIZZLE_SUFFIX
#define XXZW_ xxzw SWIZZLE_SUFFIX
#define YXZW_ yxzw SWIZZLE_SUFFIX
#define ZXZW_ zxzw SWIZZLE_SUFFIX
#define WXZW_ wxzw SWIZZLE_SUFFIX
#define XYZW_ xyzw SWIZZLE_SUFFIX
#define YYZW_ yyzw SWIZZLE_SUFFIX
#define ZYZW_ zyzw SWIZZLE_SUFFIX
#define WYZW_ wyzw SWIZZLE_SUFFIX
#define XZZW_ xzzw SWIZZLE_SUFFIX
#define YZZW_ yzzw SWIZZLE_SUFFIX
#define ZZZW_ zzzw SWIZZLE_SUFFIX
#define WZZW_ wzzw SWIZZLE_SUFFIX
#define XWZW_ xwzw SWIZZLE_SUFFIX
#define YWZW_ ywzw SWIZZLE_SUFFIX
#define ZWZW_ zwzw SWIZZLE_SUFFIX
#define WWZW_ wwzw SWIZZLE_SUFFIX
#define XXWW_ xxww SWIZZLE_SUFFIX
#define YXWW_ yxww SWIZZLE_SUFFIX
#define ZXWW_ zxww SWIZZLE_SUFFIX
#define WXWW_ wxww SWIZZLE_SUFFIX
#define XYWW_ xyww SWIZZLE_SUFFIX
#define YYWW_ yyww SWIZZLE_SUFFIX
#define ZYWW_ zyww SWIZZLE_SUFFIX
#define WYWW_ wyww SWIZZLE_SUFFIX
#define XZWW_ xzww SWIZZLE_SUFFIX
#define YZWW_ yzww SWIZZLE_SUFFIX
#define ZZWW_ zzww SWIZZLE_SUFFIX
#define WZWW_ wzww SWIZZLE_SUFFIX
#define XWWW_ xwww SWIZZLE_SUFFIX
#define YWWW_ ywww SWIZZLE_SUFFIX
#define ZWWW_ zwww SWIZZLE_SUFFIX
#define WWWW_ wwww SWIZZLE_SUFFIX

// Swizzle rgba
// Swizzle rgba with 1 components.
#define R_ r SWIZZLE_SUFFIX
#define G_ g SWIZZLE_SUFFIX
#define B_ b SWIZZLE_SUFFIX
#define A_ a SWIZZLE_SUFFIX

// Swizzle rgba with 2 components.
#define RR_ rr SWIZZLE_SUFFIX
#define GR_ gr SWIZZLE_SUFFIX
#define BR_ br SWIZZLE_SUFFIX
#define AR_ ar SWIZZLE_SUFFIX
#define RG_ rg SWIZZLE_SUFFIX
#define GG_ gg SWIZZLE_SUFFIX
#define BG_ bg SWIZZLE_SUFFIX
#define AG_ ag SWIZZLE_SUFFIX
#define RB_ rb SWIZZLE_SUFFIX
#define GB_ gb SWIZZLE_SUFFIX
#define BB_ bb SWIZZLE_SUFFIX
#define AB_ ab SWIZZLE_SUFFIX
#define RA_ ra SWIZZLE_SUFFIX
#define GA_ ga SWIZZLE_SUFFIX
#define BA_ ba SWIZZLE_SUFFIX
#define AA_ aa SWIZZLE_SUFFIX

// Swizzle rgba with 3 components.
#define RRR_ rrr SWIZZLE_SUFFIX
#define GRR_ grr SWIZZLE_SUFFIX
#define BRR_ brr SWIZZLE_SUFFIX
#define ARR_ arr SWIZZLE_SUFFIX
#define RGR_ rgr SWIZZLE_SUFFIX
#define GGR_ ggr SWIZZLE_SUFFIX
#define BGR_ bgr SWIZZLE_SUFFIX
#define AGR_ agr SWIZZLE_SUFFIX
#define RBR_ rbr SWIZZLE_SUFFIX
#define GBR_ gbr SWIZZLE_SUFFIX
#define BBR_ bbr SWIZZLE_SUFFIX
#define ABR_ abr SWIZZLE_SUFFIX
#define RAR_ rar SWIZZLE_SUFFIX
#define GAR_ gar SWIZZLE_SUFFIX
#define BAR_ bar SWIZZLE_SUFFIX
#define AAR_ aar SWIZZLE_SUFFIX
#define RRG_ rrg SWIZZLE_SUFFIX
#define GRG_ grg SWIZZLE_SUFFIX
#define BRG_ brg SWIZZLE_SUFFIX
#define ARG_ arg SWIZZLE_SUFFIX
#define RGG_ rgg SWIZZLE_SUFFIX
#define GGG_ ggg SWIZZLE_SUFFIX
#define BGG_ bgg SWIZZLE_SUFFIX
#define AGG_ agg SWIZZLE_SUFFIX
#define RBG_ rbg SWIZZLE_SUFFIX
#define GBG_ gbg SWIZZLE_SUFFIX
#define BBG_ bbg SWIZZLE_SUFFIX
#define ABG_ abg SWIZZLE_SUFFIX
#define RAG_ rag SWIZZLE_SUFFIX
#define GAG_ gag SWIZZLE_SUFFIX
#define BAG_ bag SWIZZLE_SUFFIX
#define AAG_ aag SWIZZLE_SUFFIX
#define RRB_ rrb SWIZZLE_SUFFIX
#define GRB_ grb SWIZZLE_SUFFIX
#define BRB_ brb SWIZZLE_SUFFIX
#define ARB_ arb SWIZZLE_SUFFIX
#define RGB_ rgb SWIZZLE_SUFFIX
#define GGB_ ggb SWIZZLE_SUFFIX
#define BGB_ bgb SWIZZLE_SUFFIX
#define AGB_ agb SWIZZLE_SUFFIX
#define RBB_ rbb SWIZZLE_SUFFIX
#define GBB_ gbb SWIZZLE_SUFFIX
#define BBB_ bbb SWIZZLE_SUFFIX
#define ABB_ abb SWIZZLE_SUFFIX
#define RAB_ rab SWIZZLE_SUFFIX
#define GAB_ gab SWIZZLE_SUFFIX
#define BAB_ bab SWIZZLE_SUFFIX
#define AAB_ aab SWIZZLE_SUFFIX
#define RRA_ rra SWIZZLE_SUFFIX
#define GRA_ gra SWIZZLE_SUFFIX
#define BRA_ bra SWIZZLE_SUFFIX
#define ARA_ ara SWIZZLE_SUFFIX
#define RGA_ rga SWIZZLE_SUFFIX
#define GGA_ gga SWIZZLE_SUFFIX
#define BGA_ bga SWIZZLE_SUFFIX
#define AGA_ aga SWIZZLE_SUFFIX
#define RBA_ rba SWIZZLE_SUFFIX
#define GBA_ gba SWIZZLE_SUFFIX
#define BBA_ bba SWIZZLE_SUFFIX
#define ABA_ aba SWIZZLE_SUFFIX
#define RAA_ raa SWIZZLE_SUFFIX
#define GAA_ gaa SWIZZLE_SUFFIX
#define BAA_ baa SWIZZLE_SUFFIX
#define AAA_ aaa SWIZZLE_SUFFIX

// Swizzle rgba with 4 components.
#define RRRR_ rrrr SWIZZLE_SUFFIX
#define GRRR_ grrr SWIZZLE_SUFFIX
#define BRRR_ brrr SWIZZLE_SUFFIX
#define ARRR_ arrr SWIZZLE_SUFFIX
#define RGRR_ rgrr SWIZZLE_SUFFIX
#define GGRR_ ggrr SWIZZLE_SUFFIX
#define BGRR_ bgrr SWIZZLE_SUFFIX
#define AGRR_ agrr SWIZZLE_SUFFIX
#define RBRR_ rbrr SWIZZLE_SUFFIX
#define GBRR_ gbrr SWIZZLE_SUFFIX
#define BBRR_ bbrr SWIZZLE_SUFFIX
#define ABRR_ abrr SWIZZLE_SUFFIX
#define RARR_ rarr SWIZZLE_SUFFIX
#define GARR_ garr SWIZZLE_SUFFIX
#define BARR_ barr SWIZZLE_SUFFIX
#define AARR_ aarr SWIZZLE_SUFFIX
#define RRGR_ rrgr SWIZZLE_SUFFIX
#define GRGR_ grgr SWIZZLE_SUFFIX
#define BRGR_ brgr SWIZZLE_SUFFIX
#define ARGR_ argr SWIZZLE_SUFFIX
#define RGGR_ rggr SWIZZLE_SUFFIX
#define GGGR_ gggr SWIZZLE_SUFFIX
#define BGGR_ bggr SWIZZLE_SUFFIX
#define AGGR_ aggr SWIZZLE_SUFFIX
#define RBGR_ rbgr SWIZZLE_SUFFIX
#define GBGR_ gbgr SWIZZLE_SUFFIX
#define BBGR_ bbgr SWIZZLE_SUFFIX
#define ABGR_ abgr SWIZZLE_SUFFIX
#define RAGR_ ragr SWIZZLE_SUFFIX
#define GAGR_ gagr SWIZZLE_SUFFIX
#define BAGR_ bagr SWIZZLE_SUFFIX
#define AAGR_ aagr SWIZZLE_SUFFIX
#define RRBR_ rrbr SWIZZLE_SUFFIX
#define GRBR_ grbr SWIZZLE_SUFFIX
#define BRBR_ brbr SWIZZLE_SUFFIX
#define ARBR_ arbr SWIZZLE_SUFFIX
#define RGBR_ rgbr SWIZZLE_SUFFIX
#define GGBR_ ggbr SWIZZLE_SUFFIX
#define BGBR_ bgbr SWIZZLE_SUFFIX
#define AGBR_ agbr SWIZZLE_SUFFIX
#define RBBR_ rbbr SWIZZLE_SUFFIX
#define GBBR_ gbbr SWIZZLE_SUFFIX
#define BBBR_ bbbr SWIZZLE_SUFFIX
#define ABBR_ abbr SWIZZLE_SUFFIX
#define RABR_ rabr SWIZZLE_SUFFIX
#define GABR_ gabr SWIZZLE_SUFFIX
#define BABR_ babr SWIZZLE_SUFFIX
#define AABR_ aabr SWIZZLE_SUFFIX
#define RRAR_ rrar SWIZZLE_SUFFIX
#define GRAR_ grar SWIZZLE_SUFFIX
#define BRAR_ brar SWIZZLE_SUFFIX
#define ARAR_ arar SWIZZLE_SUFFIX
#define RGAR_ rgar SWIZZLE_SUFFIX
#define GGAR_ ggar SWIZZLE_SUFFIX
#define BGAR_ bgar SWIZZLE_SUFFIX
#define AGAR_ agar SWIZZLE_SUFFIX
#define RBAR_ rbar SWIZZLE_SUFFIX
#define GBAR_ gbar SWIZZLE_SUFFIX
#define BBAR_ bbar SWIZZLE_SUFFIX
#define ABAR_ abar SWIZZLE_SUFFIX
#define RAAR_ raar SWIZZLE_SUFFIX
#define GAAR_ gaar SWIZZLE_SUFFIX
#define BAAR_ baar SWIZZLE_SUFFIX
#define AAAR_ aaar SWIZZLE_SUFFIX
#define RRRG_ rrrg SWIZZLE_SUFFIX
#define GRRG_ grrg SWIZZLE_SUFFIX
#define BRRG_ brrg SWIZZLE_SUFFIX
#define ARRG_ arrg SWIZZLE_SUFFIX
#define RGRG_ rgrg SWIZZLE_SUFFIX
#define GGRG_ ggrg SWIZZLE_SUFFIX
#define BGRG_ bgrg SWIZZLE_SUFFIX
#define AGRG_ agrg SWIZZLE_SUFFIX
#define RBRG_ rbrg SWIZZLE_SUFFIX
#define GBRG_ gbrg SWIZZLE_SUFFIX
#define BBRG_ bbrg SWIZZLE_SUFFIX
#define ABRG_ abrg SWIZZLE_SUFFIX
#define RARG_ rarg SWIZZLE_SUFFIX
#define GARG_ garg SWIZZLE_SUFFIX
#define BARG_ barg SWIZZLE_SUFFIX
#define AARG_ aarg SWIZZLE_SUFFIX
#define RRGG_ rrgg SWIZZLE_SUFFIX
#define GRGG_ grgg SWIZZLE_SUFFIX
#define BRGG_ brgg SWIZZLE_SUFFIX
#define ARGG_ argg SWIZZLE_SUFFIX
#define RGGG_ rggg SWIZZLE_SUFFIX
#define GGGG_ gggg SWIZZLE_SUFFIX
#define BGGG_ bggg SWIZZLE_SUFFIX
#define AGGG_ aggg SWIZZLE_SUFFIX
#define RBGG_ rbgg SWIZZLE_SUFFIX
#define GBGG_ gbgg SWIZZLE_SUFFIX
#define BBGG_ bbgg SWIZZLE_SUFFIX
#define ABGG_ abgg SWIZZLE_SUFFIX
#define RAGG_ ragg SWIZZLE_SUFFIX
#define GAGG_ gagg SWIZZLE_SUFFIX
#define BAGG_ bagg SWIZZLE_SUFFIX
#define AAGG_ aagg SWIZZLE_SUFFIX
#define RRBG_ rrbg SWIZZLE_SUFFIX
#define GRBG_ grbg SWIZZLE_SUFFIX
#define BRBG_ brbg SWIZZLE_SUFFIX
#define ARBG_ arbg SWIZZLE_SUFFIX
#define RGBG_ rgbg SWIZZLE_SUFFIX
#define GGBG_ ggbg SWIZZLE_SUFFIX
#define BGBG_ bgbg SWIZZLE_SUFFIX
#define AGBG_ agbg SWIZZLE_SUFFIX
#define RBBG_ rbbg SWIZZLE_SUFFIX
#define GBBG_ gbbg SWIZZLE_SUFFIX
#define BBBG_ bbbg SWIZZLE_SUFFIX
#define ABBG_ abbg SWIZZLE_SUFFIX
#define RABG_ rabg SWIZZLE_SUFFIX
#define GABG_ gabg SWIZZLE_SUFFIX
#define BABG_ babg SWIZZLE_SUFFIX
#define AABG_ aabg SWIZZLE_SUFFIX
#define RRAG_ rrag SWIZZLE_SUFFIX
#define GRAG_ grag SWIZZLE_SUFFIX
#define BRAG_ brag SWIZZLE_SUFFIX
#define ARAG_ arag SWIZZLE_SUFFIX
#define RGAG_ rgag SWIZZLE_SUFFIX
#define GGAG_ ggag SWIZZLE_SUFFIX
#define BGAG_ bgag SWIZZLE_SUFFIX
#define AGAG_ agag SWIZZLE_SUFFIX
#define RBAG_ rbag SWIZZLE_SUFFIX
#define GBAG_ gbag SWIZZLE_SUFFIX
#define BBAG_ bbag SWIZZLE_SUFFIX
#define ABAG_ abag SWIZZLE_SUFFIX
#define RAAG_ raag SWIZZLE_SUFFIX
#define GAAG_ gaag SWIZZLE_SUFFIX
#define BAAG_ baag SWIZZLE_SUFFIX
#define AAAG_ aaag SWIZZLE_SUFFIX
#define RRRB_ rrrb SWIZZLE_SUFFIX
#define GRRB_ grrb SWIZZLE_SUFFIX
#define BRRB_ brrb SWIZZLE_SUFFIX
#define ARRB_ arrb SWIZZLE_SUFFIX
#define RGRB_ rgrb SWIZZLE_SUFFIX
#define GGRB_ ggrb SWIZZLE_SUFFIX
#define BGRB_ bgrb SWIZZLE_SUFFIX
#define AGRB_ agrb SWIZZLE_SUFFIX
#define RBRB_ rbrb SWIZZLE_SUFFIX
#define GBRB_ gbrb SWIZZLE_SUFFIX
#define BBRB_ bbrb SWIZZLE_SUFFIX
#define ABRB_ abrb SWIZZLE_SUFFIX
#define RARB_ rarb SWIZZLE_SUFFIX
#define GARB_ garb SWIZZLE_SUFFIX
#define BARB_ barb SWIZZLE_SUFFIX
#define AARB_ aarb SWIZZLE_SUFFIX
#define RRGB_ rrgb SWIZZLE_SUFFIX
#define GRGB_ grgb SWIZZLE_SUFFIX
#define BRGB_ brgb SWIZZLE_SUFFIX
#define ARGB_ argb SWIZZLE_SUFFIX
#define RGGB_ rggb SWIZZLE_SUFFIX
#define GGGB_ gggb SWIZZLE_SUFFIX
#define BGGB_ bggb SWIZZLE_SUFFIX
#define AGGB_ aggb SWIZZLE_SUFFIX
#define RBGB_ rbgb SWIZZLE_SUFFIX
#define GBGB_ gbgb SWIZZLE_SUFFIX
#define BBGB_ bbgb SWIZZLE_SUFFIX
#define ABGB_ abgb SWIZZLE_SUFFIX
#define RAGB_ ragb SWIZZLE_SUFFIX
#define GAGB_ gagb SWIZZLE_SUFFIX
#define BAGB_ bagb SWIZZLE_SUFFIX
#define AAGB_ aagb SWIZZLE_SUFFIX
#define RRBB_ rrbb SWIZZLE_SUFFIX
#define GRBB_ grbb SWIZZLE_SUFFIX
#define BRBB_ brbb SWIZZLE_SUFFIX
#define ARBB_ arbb SWIZZLE_SUFFIX
#define RGBB_ rgbb SWIZZLE_SUFFIX
#define GGBB_ ggbb SWIZZLE_SUFFIX
#define BGBB_ bgbb SWIZZLE_SUFFIX
#define AGBB_ agbb SWIZZLE_SUFFIX
#define RBBB_ rbbb SWIZZLE_SUFFIX
#define GBBB_ gbbb SWIZZLE_SUFFIX
#define BBBB_ bbbb SWIZZLE_SUFFIX
#define ABBB_ abbb SWIZZLE_SUFFIX
#define RABB_ rabb SWIZZLE_SUFFIX
#define GABB_ gabb SWIZZLE_SUFFIX
#define BABB_ babb SWIZZLE_SUFFIX
#define AABB_ aabb SWIZZLE_SUFFIX
#define RRAB_ rrab SWIZZLE_SUFFIX
#define GRAB_ grab SWIZZLE_SUFFIX
#define BRAB_ brab SWIZZLE_SUFFIX
#define ARAB_ arab SWIZZLE_SUFFIX
#define RGAB_ rgab SWIZZLE_SUFFIX
#define GGAB_ ggab SWIZZLE_SUFFIX
#define BGAB_ bgab SWIZZLE_SUFFIX
#define AGAB_ agab SWIZZLE_SUFFIX
#define RBAB_ rbab SWIZZLE_SUFFIX
#define GBAB_ gbab SWIZZLE_SUFFIX
#define BBAB_ bbab SWIZZLE_SUFFIX
#define ABAB_ abab SWIZZLE_SUFFIX
#define RAAB_ raab SWIZZLE_SUFFIX
#define GAAB_ gaab SWIZZLE_SUFFIX
#define BAAB_ baab SWIZZLE_SUFFIX
#define AAAB_ aaab SWIZZLE_SUFFIX
#define RRRA_ rrra SWIZZLE_SUFFIX
#define GRRA_ grra SWIZZLE_SUFFIX
#define BRRA_ brra SWIZZLE_SUFFIX
#define ARRA_ arra SWIZZLE_SUFFIX
#define RGRA_ rgra SWIZZLE_SUFFIX
#define GGRA_ ggra SWIZZLE_SUFFIX
#define BGRA_ bgra SWIZZLE_SUFFIX
#define AGRA_ agra SWIZZLE_SUFFIX
#define RBRA_ rbra SWIZZLE_SUFFIX
#define GBRA_ gbra SWIZZLE_SUFFIX
#define BBRA_ bbra SWIZZLE_SUFFIX
#define ABRA_ abra SWIZZLE_SUFFIX
#define RARA_ rara SWIZZLE_SUFFIX
#define GARA_ gara SWIZZLE_SUFFIX
#define BARA_ bara SWIZZLE_SUFFIX
#define AARA_ aara SWIZZLE_SUFFIX
#define RRGA_ rrga SWIZZLE_SUFFIX
#define GRGA_ grga SWIZZLE_SUFFIX
#define BRGA_ brga SWIZZLE_SUFFIX
#define ARGA_ arga SWIZZLE_SUFFIX
#define RGGA_ rgga SWIZZLE_SUFFIX
#define GGGA_ ggga SWIZZLE_SUFFIX
#define BGGA_ bgga SWIZZLE_SUFFIX
#define AGGA_ agga SWIZZLE_SUFFIX
#define RBGA_ rbga SWIZZLE_SUFFIX
#define GBGA_ gbga SWIZZLE_SUFFIX
#define BBGA_ bbga SWIZZLE_SUFFIX
#define ABGA_ abga SWIZZLE_SUFFIX
#define RAGA_ raga SWIZZLE_SUFFIX
#define GAGA_ gaga SWIZZLE_SUFFIX
#define BAGA_ baga SWIZZLE_SUFFIX
#define AAGA_ aaga SWIZZLE_SUFFIX
#define RRBA_ rrba SWIZZLE_SUFFIX
#define GRBA_ grba SWIZZLE_SUFFIX
#define BRBA_ brba SWIZZLE_SUFFIX
#define ARBA_ arba SWIZZLE_SUFFIX
#define RGBA_ rgba SWIZZLE_SUFFIX
#define GGBA_ ggba SWIZZLE_SUFFIX
#define BGBA_ bgba SWIZZLE_SUFFIX
#define AGBA_ agba SWIZZLE_SUFFIX
#define RBBA_ rbba SWIZZLE_SUFFIX
#define GBBA_ gbba SWIZZLE_SUFFIX
#define BBBA_ bbba SWIZZLE_SUFFIX
#define ABBA_ abba SWIZZLE_SUFFIX
#define RABA_ raba SWIZZLE_SUFFIX
#define GABA_ gaba SWIZZLE_SUFFIX
#define BABA_ baba SWIZZLE_SUFFIX
#define AABA_ aaba SWIZZLE_SUFFIX
#define RRAA_ rraa SWIZZLE_SUFFIX
#define GRAA_ graa SWIZZLE_SUFFIX
#define BRAA_ braa SWIZZLE_SUFFIX
#define ARAA_ araa SWIZZLE_SUFFIX
#define RGAA_ rgaa SWIZZLE_SUFFIX
#define GGAA_ ggaa SWIZZLE_SUFFIX
#define BGAA_ bgaa SWIZZLE_SUFFIX
#define AGAA_ agaa SWIZZLE_SUFFIX
#define RBAA_ rbaa SWIZZLE_SUFFIX
#define GBAA_ gbaa SWIZZLE_SUFFIX
#define BBAA_ bbaa SWIZZLE_SUFFIX
#define ABAA_ abaa SWIZZLE_SUFFIX
#define RAAA_ raaa SWIZZLE_SUFFIX
#define GAAA_ gaaa SWIZZLE_SUFFIX
#define BAAA_ baaa SWIZZLE_SUFFIX
#define AAAA_ aaaa SWIZZLE_SUFFIX

// Swizzle stpq
// Swizzle stpq with 1 components.
#define S_ s SWIZZLE_SUFFIX
#define T_ t SWIZZLE_SUFFIX
#define P_ p SWIZZLE_SUFFIX
#define Q_ q SWIZZLE_SUFFIX

// Swizzle stpq with 2 components.
#define SS_ ss SWIZZLE_SUFFIX
#define TS_ ts SWIZZLE_SUFFIX
#define PS_ ps SWIZZLE_SUFFIX
#define QS_ qs SWIZZLE_SUFFIX
#define ST_ st SWIZZLE_SUFFIX
#define TT_ tt SWIZZLE_SUFFIX
#define PT_ pt SWIZZLE_SUFFIX
#define QT_ qt SWIZZLE_SUFFIX
#define SP_ sp SWIZZLE_SUFFIX
#define TP_ tp SWIZZLE_SUFFIX
#define PP_ pp SWIZZLE_SUFFIX
#define QP_ qp SWIZZLE_SUFFIX
#define SQ_ sq SWIZZLE_SUFFIX
#define TQ_ tq SWIZZLE_SUFFIX
#define PQ_ pq SWIZZLE_SUFFIX
#define QQ_ qq SWIZZLE_SUFFIX

// Swizzle stpq with 3 components.
#define SSS_ sss SWIZZLE_SUFFIX
#define TSS_ tss SWIZZLE_SUFFIX
#define PSS_ pss SWIZZLE_SUFFIX
#define QSS_ qss SWIZZLE_SUFFIX
#define STS_ sts SWIZZLE_SUFFIX
#define TTS_ tts SWIZZLE_SUFFIX
#define PTS_ pts SWIZZLE_SUFFIX
#define QTS_ qts SWIZZLE_SUFFIX
#define SPS_ sps SWIZZLE_SUFFIX
#define TPS_ tps SWIZZLE_SUFFIX
#define PPS_ pps SWIZZLE_SUFFIX
#define QPS_ qps SWIZZLE_SUFFIX
#define SQS_ sqs SWIZZLE_SUFFIX
#define TQS_ tqs SWIZZLE_SUFFIX
#define PQS_ pqs SWIZZLE_SUFFIX
#define QQS_ qqs SWIZZLE_SUFFIX
#define SST_ sst SWIZZLE_SUFFIX
#define TST_ tst SWIZZLE_SUFFIX
#define PST_ pst SWIZZLE_SUFFIX
#define QST_ qst SWIZZLE_SUFFIX
#define STT_ stt SWIZZLE_SUFFIX
#define TTT_ ttt SWIZZLE_SUFFIX
#define PTT_ ptt SWIZZLE_SUFFIX
#define QTT_ qtt SWIZZLE_SUFFIX
#define SPT_ spt SWIZZLE_SUFFIX
#define TPT_ tpt SWIZZLE_SUFFIX
#define PPT_ ppt SWIZZLE_SUFFIX
#define QPT_ qpt SWIZZLE_SUFFIX
#define SQT_ sqt SWIZZLE_SUFFIX
#define TQT_ tqt SWIZZLE_SUFFIX
#define PQT_ pqt SWIZZLE_SUFFIX
#define QQT_ qqt SWIZZLE_SUFFIX
#define SSP_ ssp SWIZZLE_SUFFIX
#define TSP_ tsp SWIZZLE_SUFFIX
#define PSP_ psp SWIZZLE_SUFFIX
#define QSP_ qsp SWIZZLE_SUFFIX
#define STP_ stp SWIZZLE_SUFFIX
#define TTP_ ttp SWIZZLE_SUFFIX
#define PTP_ ptp SWIZZLE_SUFFIX
#define QTP_ qtp SWIZZLE_SUFFIX
#define SPP_ spp SWIZZLE_SUFFIX
#define TPP_ tpp SWIZZLE_SUFFIX
#define PPP_ ppp SWIZZLE_SUFFIX
#define QPP_ qpp SWIZZLE_SUFFIX
#define SQP_ sqp SWIZZLE_SUFFIX
#define TQP_ tqp SWIZZLE_SUFFIX
#define PQP_ pqp SWIZZLE_SUFFIX
#define QQP_ qqp SWIZZLE_SUFFIX
#define SSQ_ ssq SWIZZLE_SUFFIX
#define TSQ_ tsq SWIZZLE_SUFFIX
#define PSQ_ psq SWIZZLE_SUFFIX
#define QSQ_ qsq SWIZZLE_SUFFIX
#define STQ_ stq SWIZZLE_SUFFIX
#define TTQ_ ttq SWIZZLE_SUFFIX
#define PTQ_ ptq SWIZZLE_SUFFIX
#define QTQ_ qtq SWIZZLE_SUFFIX
#define SPQ_ spq SWIZZLE_SUFFIX
#define TPQ_ tpq SWIZZLE_SUFFIX
#define PPQ_ ppq SWIZZLE_SUFFIX
#define QPQ_ qpq SWIZZLE_SUFFIX
#define SQQ_ sqq SWIZZLE_SUFFIX
#define TQQ_ tqq SWIZZLE_SUFFIX
#define PQQ_ pqq SWIZZLE_SUFFIX
#define QQQ_ qqq SWIZZLE_SUFFIX

// Swizzle stpq with 4 components.
#define SSSS_ ssss SWIZZLE_SUFFIX
#define TSSS_ tsss SWIZZLE_SUFFIX
#define PSSS_ psss SWIZZLE_SUFFIX
#define QSSS_ qsss SWIZZLE_SUFFIX
#define STSS_ stss SWIZZLE_SUFFIX
#define TTSS_ ttss SWIZZLE_SUFFIX
#define PTSS_ ptss SWIZZLE_SUFFIX
#define QTSS_ qtss SWIZZLE_SUFFIX
#define SPSS_ spss SWIZZLE_SUFFIX
#define TPSS_ tpss SWIZZLE_SUFFIX
#define PPSS_ ppss SWIZZLE_SUFFIX
#define QPSS_ qpss SWIZZLE_SUFFIX
#define SQSS_ sqss SWIZZLE_SUFFIX
#define TQSS_ tqss SWIZZLE_SUFFIX
#define PQSS_ pqss SWIZZLE_SUFFIX
#define QQSS_ qqss SWIZZLE_SUFFIX
#define SSTS_ ssts SWIZZLE_SUFFIX
#define TSTS_ tsts SWIZZLE_SUFFIX
#define PSTS_ psts SWIZZLE_SUFFIX
#define QSTS_ qsts SWIZZLE_SUFFIX
#define STTS_ stts SWIZZLE_SUFFIX
#define TTTS_ ttts SWIZZLE_SUFFIX
#define PTTS_ ptts SWIZZLE_SUFFIX
#define QTTS_ qtts SWIZZLE_SUFFIX
#define SPTS_ spts SWIZZLE_SUFFIX
#define TPTS_ tpts SWIZZLE_SUFFIX
#define PPTS_ ppts SWIZZLE_SUFFIX
#define QPTS_ qpts SWIZZLE_SUFFIX
#define SQTS_ sqts SWIZZLE_SUFFIX
#define TQTS_ tqts SWIZZLE_SUFFIX
#define PQTS_ pqts SWIZZLE_SUFFIX
#define QQTS_ qqts SWIZZLE_SUFFIX
#define SSPS_ ssps SWIZZLE_SUFFIX
#define TSPS_ tsps SWIZZLE_SUFFIX
#define PSPS_ psps SWIZZLE_SUFFIX
#define QSPS_ qsps SWIZZLE_SUFFIX
#define STPS_ stps SWIZZLE_SUFFIX
#define TTPS_ ttps SWIZZLE_SUFFIX
#define PTPS_ ptps SWIZZLE_SUFFIX
#define QTPS_ qtps SWIZZLE_SUFFIX
#define SPPS_ spps SWIZZLE_SUFFIX
#define TPPS_ tpps SWIZZLE_SUFFIX
#define PPPS_ ppps SWIZZLE_SUFFIX
#define QPPS_ qpps SWIZZLE_SUFFIX
#define SQPS_ sqps SWIZZLE_SUFFIX
#define TQPS_ tqps SWIZZLE_SUFFIX
#define PQPS_ pqps SWIZZLE_SUFFIX
#define QQPS_ qqps SWIZZLE_SUFFIX
#define SSQS_ ssqs SWIZZLE_SUFFIX
#define TSQS_ tsqs SWIZZLE_SUFFIX
#define PSQS_ psqs SWIZZLE_SUFFIX
#define QSQS_ qsqs SWIZZLE_SUFFIX
#define STQS_ stqs SWIZZLE_SUFFIX
#define TTQS_ ttqs SWIZZLE_SUFFIX
#define PTQS_ ptqs SWIZZLE_SUFFIX
#define QTQS_ qtqs SWIZZLE_SUFFIX
#define SPQS_ spqs SWIZZLE_SUFFIX
#define TPQS_ tpqs SWIZZLE_SUFFIX
#define PPQS_ ppqs SWIZZLE_SUFFIX
#define QPQS_ qpqs SWIZZLE_SUFFIX
#define SQQS_ sqqs SWIZZLE_SUFFIX
#define TQQS_ tqqs SWIZZLE_SUFFIX
#define PQQS_ pqqs SWIZZLE_SUFFIX
#define QQQS_ qqqs SWIZZLE_SUFFIX
#define SSST_ ssst SWIZZLE_SUFFIX
#define TSST_ tsst SWIZZLE_SUFFIX
#define PSST_ psst SWIZZLE_SUFFIX
#define QSST_ qsst SWIZZLE_SUFFIX
#define STST_ stst SWIZZLE_SUFFIX
#define TTST_ ttst SWIZZLE_SUFFIX
#define PTST_ ptst SWIZZLE_SUFFIX
#define QTST_ qtst SWIZZLE_SUFFIX
#define SPST_ spst SWIZZLE_SUFFIX
#define TPST_ tpst SWIZZLE_SUFFIX
#define PPST_ ppst SWIZZLE_SUFFIX
#define QPST_ qpst SWIZZLE_SUFFIX
#define SQST_ sqst SWIZZLE_SUFFIX
#define TQST_ tqst SWIZZLE_SUFFIX
#define PQST_ pqst SWIZZLE_SUFFIX
#define QQST_ qqst SWIZZLE_SUFFIX
#define SSTT_ sstt SWIZZLE_SUFFIX
#define TSTT_ tstt SWIZZLE_SUFFIX
#define PSTT_ pstt SWIZZLE_SUFFIX
#define QSTT_ qstt SWIZZLE_SUFFIX
#define STTT_ sttt SWIZZLE_SUFFIX
#define TTTT_ tttt SWIZZLE_SUFFIX
#define PTTT_ pttt SWIZZLE_SUFFIX
#define QTTT_ qttt SWIZZLE_SUFFIX
#define SPTT_ sptt SWIZZLE_SUFFIX
#define TPTT_ tptt SWIZZLE_SUFFIX
#define PPTT_ pptt SWIZZLE_SUFFIX
#define QPTT_ qptt SWIZZLE_SUFFIX
#define SQTT_ sqtt SWIZZLE_SUFFIX
#define TQTT_ tqtt SWIZZLE_SUFFIX
#define PQTT_ pqtt SWIZZLE_SUFFIX
#define QQTT_ qqtt SWIZZLE_SUFFIX
#define SSPT_ sspt SWIZZLE_SUFFIX
#define TSPT_ tspt SWIZZLE_SUFFIX
#define PSPT_ pspt SWIZZLE_SUFFIX
#define QSPT_ qspt SWIZZLE_SUFFIX
#define STPT_ stpt SWIZZLE_SUFFIX
#define TTPT_ ttpt SWIZZLE_SUFFIX
#define PTPT_ ptpt SWIZZLE_SUFFIX
#define QTPT_ qtpt SWIZZLE_SUFFIX
#define SPPT_ sppt SWIZZLE_SUFFIX
#define TPPT_ tppt SWIZZLE_SUFFIX
#define PPPT_ pppt SWIZZLE_SUFFIX
#define QPPT_ qppt SWIZZLE_SUFFIX
#define SQPT_ sqpt SWIZZLE_SUFFIX
#define TQPT_ tqpt SWIZZLE_SUFFIX
#define PQPT_ pqpt SWIZZLE_SUFFIX
#define QQPT_ qqpt SWIZZLE_SUFFIX
#define SSQT_ ssqt SWIZZLE_SUFFIX
#define TSQT_ tsqt SWIZZLE_SUFFIX
#define PSQT_ psqt SWIZZLE_SUFFIX
#define QSQT_ qsqt SWIZZLE_SUFFIX
#define STQT_ stqt SWIZZLE_SUFFIX
#define TTQT_ ttqt SWIZZLE_SUFFIX
#define PTQT_ ptqt SWIZZLE_SUFFIX
#define QTQT_ qtqt SWIZZLE_SUFFIX
#define SPQT_ spqt SWIZZLE_SUFFIX
#define TPQT_ tpqt SWIZZLE_SUFFIX
#define PPQT_ ppqt SWIZZLE_SUFFIX
#define QPQT_ qpqt SWIZZLE_SUFFIX
#define SQQT_ sqqt SWIZZLE_SUFFIX
#define TQQT_ tqqt SWIZZLE_SUFFIX
#define PQQT_ pqqt SWIZZLE_SUFFIX
#define QQQT_ qqqt SWIZZLE_SUFFIX
#define SSSP_ sssp SWIZZLE_SUFFIX
#define TSSP_ tssp SWIZZLE_SUFFIX
#define PSSP_ pssp SWIZZLE_SUFFIX
#define QSSP_ qssp SWIZZLE_SUFFIX
#define STSP_ stsp SWIZZLE_SUFFIX
#define TTSP_ ttsp SWIZZLE_SUFFIX
#define PTSP_ ptsp SWIZZLE_SUFFIX
#define QTSP_ qtsp SWIZZLE_SUFFIX
#define SPSP_ spsp SWIZZLE_SUFFIX
#define TPSP_ tpsp SWIZZLE_SUFFIX
#define PPSP_ ppsp SWIZZLE_SUFFIX
#define QPSP_ qpsp SWIZZLE_SUFFIX
#define SQSP_ sqsp SWIZZLE_SUFFIX
#define TQSP_ tqsp SWIZZLE_SUFFIX
#define PQSP_ pqsp SWIZZLE_SUFFIX
#define QQSP_ qqsp SWIZZLE_SUFFIX
#define SSTP_ sstp SWIZZLE_SUFFIX
#define TSTP_ tstp SWIZZLE_SUFFIX
#define PSTP_ pstp SWIZZLE_SUFFIX
#define QSTP_ qstp SWIZZLE_SUFFIX
#define STTP_ sttp SWIZZLE_SUFFIX
#define TTTP_ tttp SWIZZLE_SUFFIX
#define PTTP_ pttp SWIZZLE_SUFFIX
#define QTTP_ qttp SWIZZLE_SUFFIX
#define SPTP_ sptp SWIZZLE_SUFFIX
#define TPTP_ tptp SWIZZLE_SUFFIX
#define PPTP_ pptp SWIZZLE_SUFFIX
#define QPTP_ qptp SWIZZLE_SUFFIX
#define SQTP_ sqtp SWIZZLE_SUFFIX
#define TQTP_ tqtp SWIZZLE_SUFFIX
#define PQTP_ pqtp SWIZZLE_SUFFIX
#define QQTP_ qqtp SWIZZLE_SUFFIX
#define SSPP_ sspp SWIZZLE_SUFFIX
#define TSPP_ tspp SWIZZLE_SUFFIX
#define PSPP_ pspp SWIZZLE_SUFFIX
#define QSPP_ qspp SWIZZLE_SUFFIX
#define STPP_ stpp SWIZZLE_SUFFIX
#define TTPP_ ttpp SWIZZLE_SUFFIX
#define PTPP_ ptpp SWIZZLE_SUFFIX
#define QTPP_ qtpp SWIZZLE_SUFFIX
#define SPPP_ sppp SWIZZLE_SUFFIX
#define TPPP_ tppp SWIZZLE_SUFFIX
#define PPPP_ pppp SWIZZLE_SUFFIX
#define QPPP_ qppp SWIZZLE_SUFFIX
#define SQPP_ sqpp SWIZZLE_SUFFIX
#define TQPP_ tqpp SWIZZLE_SUFFIX
#define PQPP_ pqpp SWIZZLE_SUFFIX
#define QQPP_ qqpp SWIZZLE_SUFFIX
#define SSQP_ ssqp SWIZZLE_SUFFIX
#define TSQP_ tsqp SWIZZLE_SUFFIX
#define PSQP_ psqp SWIZZLE_SUFFIX
#define QSQP_ qsqp SWIZZLE_SUFFIX
#define STQP_ stqp SWIZZLE_SUFFIX
#define TTQP_ ttqp SWIZZLE_SUFFIX
#define PTQP_ ptqp SWIZZLE_SUFFIX
#define QTQP_ qtqp SWIZZLE_SUFFIX
#define SPQP_ spqp SWIZZLE_SUFFIX
#define TPQP_ tpqp SWIZZLE_SUFFIX
#define PPQP_ ppqp SWIZZLE_SUFFIX
#define QPQP_ qpqp SWIZZLE_SUFFIX
#define SQQP_ sqqp SWIZZLE_SUFFIX
#define TQQP_ tqqp SWIZZLE_SUFFIX
#define PQQP_ pqqp SWIZZLE_SUFFIX
#define QQQP_ qqqp SWIZZLE_SUFFIX
#define SSSQ_ sssq SWIZZLE_SUFFIX
#define TSSQ_ tssq SWIZZLE_SUFFIX
#define PSSQ_ pssq SWIZZLE_SUFFIX
#define QSSQ_ qssq SWIZZLE_SUFFIX
#define STSQ_ stsq SWIZZLE_SUFFIX
#define TTSQ_ ttsq SWIZZLE_SUFFIX
#define PTSQ_ ptsq SWIZZLE_SUFFIX
#define QTSQ_ qtsq SWIZZLE_SUFFIX
#define SPSQ_ spsq SWIZZLE_SUFFIX
#define TPSQ_ tpsq SWIZZLE_SUFFIX
#define PPSQ_ ppsq SWIZZLE_SUFFIX
#define QPSQ_ qpsq SWIZZLE_SUFFIX
#define SQSQ_ sqsq SWIZZLE_SUFFIX
#define TQSQ_ tqsq SWIZZLE_SUFFIX
#define PQSQ_ pqsq SWIZZLE_SUFFIX
#define QQSQ_ qqsq SWIZZLE_SUFFIX
#define SSTQ_ sstq SWIZZLE_SUFFIX
#define TSTQ_ tstq SWIZZLE_SUFFIX
#define PSTQ_ pstq SWIZZLE_SUFFIX
#define QSTQ_ qstq SWIZZLE_SUFFIX
#define STTQ_ sttq SWIZZLE_SUFFIX
#define TTTQ_ tttq SWIZZLE_SUFFIX
#define PTTQ_ pttq SWIZZLE_SUFFIX
#define QTTQ_ qttq SWIZZLE_SUFFIX
#define SPTQ_ sptq SWIZZLE_SUFFIX
#define TPTQ_ tptq SWIZZLE_SUFFIX
#define PPTQ_ pptq SWIZZLE_SUFFIX
#define QPTQ_ qptq SWIZZLE_SUFFIX
#define SQTQ_ sqtq SWIZZLE_SUFFIX
#define TQTQ_ tqtq SWIZZLE_SUFFIX
#define PQTQ_ pqtq SWIZZLE_SUFFIX
#define QQTQ_ qqtq SWIZZLE_SUFFIX
#define SSPQ_ sspq SWIZZLE_SUFFIX
#define TSPQ_ tspq SWIZZLE_SUFFIX
#define PSPQ_ pspq SWIZZLE_SUFFIX
#define QSPQ_ qspq SWIZZLE_SUFFIX
#define STPQ_ stpq SWIZZLE_SUFFIX
#define TTPQ_ ttpq SWIZZLE_SUFFIX
#define PTPQ_ ptpq SWIZZLE_SUFFIX
#define QTPQ_ qtpq SWIZZLE_SUFFIX
#define SPPQ_ sppq SWIZZLE_SUFFIX
#define TPPQ_ tppq SWIZZLE_SUFFIX
#define PPPQ_ pppq SWIZZLE_SUFFIX
#define QPPQ_ qppq SWIZZLE_SUFFIX
#define SQPQ_ sqpq SWIZZLE_SUFFIX
#define TQPQ_ tqpq SWIZZLE_SUFFIX
#define PQPQ_ pqpq SWIZZLE_SUFFIX
#define QQPQ_ qqpq SWIZZLE_SUFFIX
#define SSQQ_ ssqq SWIZZLE_SUFFIX
#define TSQQ_ tsqq SWIZZLE_SUFFIX
#define PSQQ_ psqq SWIZZLE_SUFFIX
#define QSQQ_ qsqq SWIZZLE_SUFFIX
#define STQQ_ stqq SWIZZLE_SUFFIX
#define TTQQ_ ttqq SWIZZLE_SUFFIX
#define PTQQ_ ptqq SWIZZLE_SUFFIX
#define QTQQ_ qtqq SWIZZLE_SUFFIX
#define SPQQ_ spqq SWIZZLE_SUFFIX
#define TPQQ_ tpqq SWIZZLE_SUFFIX
#define PPQQ_ ppqq SWIZZLE_SUFFIX
#define QPQQ_ qpqq SWIZZLE_SUFFIX
#define SQQQ_ sqqq SWIZZLE_SUFFIX
#define TQQQ_ tqqq SWIZZLE_SUFFIX
#define PQQQ_ pqqq SWIZZLE_SUFFIX
#define QQQQ_ qqqq SWIZZLE_SUFFIX
